version: "3.8"

services:
  local-db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - ./volume/mysql:/var/lib/mysql

    ports:
      - "3307:3306"

  local-web:
    restart: on-failure

    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: ${DB_DRIVER}

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: ${WEB_PROFILE}
        JASYPT_ENCRYPTOR_PASSWORD: ${WEB_JASYPT_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - local-db
