jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onboarding?serverTimezone=UTC
    username: ENC(1/TCeEOMvacwucRrkhJQfw==)
    password: ENC(PwKfTmzrh4W8BB5UXfCXRQ==)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  header: Authorization
  # #HS512 알고리즘을 사용
  secret-key: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
  token-validity-in-seconds: 86400