spring:
  datasource:
    url: ENC(uX1DLPFfJBKZagDjLPfQL8g+aaKjw4R7h6WAPJqLpJyrUdRtgLDDfvkRx/46KN3gYR3CImd970aSPvkmuBbiSnuSj3xgo1eac6uBTz9KTJT0U3N6NNajS75xbqV0Fl+7XvYB3Azm4XgqWcavxQcYilUwbklPb7q8eoEZvahUDgdX+HXSPoOMfND6ujhp+BU6)
    username: ENC(1/TCeEOMvacwucRrkhJQfw==)
    password: ENC(e5Q22H5HOIqpx6THA5goBQ==)
  jpa:
    database: mysql
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jasypt:
  encryptor:
    bean: jasyptEncryptorAES

jwt:
  header: Authorization
  secret-key: ENC(XSpRq78Ndj/oX3clzShH/+f0kt9bElNi5EcbTkBqOfat/Cj8bB7qUwGe/PuzFSnXSX72NStvnafxtU5UMzjY3PSERnbvsvlU4UqDLtDMPLXR9Gqs1HAt1+L6pH1dsxpGFpFRqpa/EUx/n+SDnlg8f0C02C+OHQRRdJlEon5IFUqcjaUzBoHoqQiSJC1XQGf8)
  token-validity-in-seconds: ENC(o0tuuMJU/8L1pM2Tq/wTXA==)